apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minify
  namespace: minify
spec:
  ingressClassName: traefik
  rules:
    # frontend url
    - host: app.129.153.59.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
    # backend API + short-link redirects 
    - host: api.129.153.59.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
