apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minify

resources:
- namespace.yaml
- postgres.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml

images:
- name: ghcr.io/sameersaeed/minify-backend
  newTag: 74d0fe68
- name: ghcr.io/sameersaeed/minify-frontend
  newTag: 74d0fe68
