# Template for what"minify-secrets" needs, 
# the real secret was manually created on the cluster 
apiVersion: v1
kind: Secret
metadata:
  name: minify-secrets
  namespace: minify
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:<password>@postgres.minify.svc.cluster.local:5432/minify?sslmode=disable"
  POSTGRES_PASSWORD: "<password>"
  JWT_SECRET: "<randomly-generated-secret>"
